# This Python file uses the following encoding: utf-8
import sys

from PySide6.QtWidgets import QApplication, QMainWindow

# --------------------------------------------------------------------
# The ui_form.py file is generated by pyside6-uic.
# If compiled using colcon build, the script that generates it is written in setup.py under the convert_ui() function.
# If compiled using Qt Creator 14, it will automatically convert the .ui file.
from ui_form import Ui_MainWindow
# --------------------------------------------------------------------
import rclpy
from rclpy.node import Node
from std_msgs.msg import String

class MainWindow(QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.node = Node("ros2_pyqt_demo")

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.ui.btn_pub_topic.clicked.connect(self.publish_message)

    def publish_message(self):
        self.publisher_ = self.node.create_publisher(String, "chatter", 10)
        msg = String()
        msg.data = "Hello from PySide6 UI!"
        self.publisher_.publish(msg)
        print("Published:", msg.data)

def main(args=None):
    rclpy.init(args=args)

    app = QApplication(sys.argv)
    widget = MainWindow()
    widget.show()

    executor = rclpy.executors.SingleThreadedExecutor()
    executor.add_node(widget.node)

    try:
        sys.exit(app.exec())
    finally:
        widget.destroy_node()
        rclpy.shutdown()

if __name__ == "__main__":
    main()